name: Sync Gitee to GitHub and Deploy to Netlify

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一执行一次，UTC 时间
  workflow_dispatch:  # 手动触发工作流
  
jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "darkersu"
          git config --global user.email "sxp_developer@163.com"

      - name: Clone Gitee repository
        run: |
          git clone https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/magic_developer/iknows.git gitee-repo
          cd gitee-repo

      - name: Copy files from Gitee to GitHub
        run: |
         rsync -av --exclude='.git' gitee-repo/ .
          ls -a 
          
      - name: Commit and push changes to GitHub
        run: |
          git add .
          git commit -m "Sync from Gitee to GitHub"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/magic857/iknow.git HEAD:dev  # 或你要同步到的分支
               
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: npm install

      - name: Build project
        run: |
          npm run docs:build  # Run the build command
      
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.vitepress/dist --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
       
