name: Sync Gitee to GitHub and Deploy to Netlify

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一执行一次，UTC 时间
  workflow_dispatch:  # 手动触发工作流
  
jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块克隆

      - name: Set up Git
        run: |
          git config --global user.name "darkersu"
          git config --global user.email "sxp_developer@163.com"

      # 克隆gitee仓库代码
      - name: Clone Gitee repository
        run: |
          git clone https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/magic_developer/iknows.git iknows
          cd iknows
          # 如果需要获取子模块
          # git submodule update --init --recursive
          
      # 复制到指定目录
      - name: Copy files from Gitee to GitHub
        run: |
          # rsync -av --exclude='.git' iknows/ .
          rsync -av iknows/ .
          ls -a 
          
      # 安装依赖
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: npm install
      
      # 构建项目
      - name: Build project
        run: |
          npm run docs:build  # Run the build command
          ls -a .vitepress/dist

      # 推送构建内容到 GitHub deploy 分支
      - name: Deploy to GitHub deploy branch
        run: |
          cd .vitepress/dist
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/magic857/iknow.git 
          git checkout -b deploy
          git add .
          git commit -m "Deploy site"
          git push --force origin deploy
      
      # - name: Commit and push changes to GitHub
      #   run: |
      #     git add .
      #     git commit -m "Sync from Gitee to GitHub"
      #     git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/magic857/iknow.git HEAD:gitee-sync  # 或你要同步到的分支  
               
      # - name: Install dependencies
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
          
      # - run: npm install

      # - name: Build project
      #   run: |
      #     npm run docs:build  # Run the build command
      #     ls -a
      
      # - name: Push build to deploy branch
      #   run: |
      #     # Make sure to clean up the repository before pushing to deploy branch
      #     git checkout --orphan deploy  # Create an orphan branch named deploy
      #     git rm -rf .  # Remove all files from the branch
      #     cp -r .vitepress/dist/* .  # Copy build output to the root of the deploy branch
      #     git add .
      #     git commit -m "Deploy build to deploy branch"
      #     git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/magic857/iknow.git HEAD:deploy

      # - name: Deploy to Netlify
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=.vitepress/dist --prod
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
       
